/*
 * This source file was generated by the Gradle 'init' task
 */
package txst.myApp;

public class App {
    public String getGreeting() {
        return "Hello World! I am trying out Gradle.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
